version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.18.4

    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - v1-dependencies-{{checksum "package-lock.json"}}
            - v1-dependencies-
      - run:
          name: install packages
          command: npm ci
      - save_cache:
          key: v1-dependencies-{{checksum "package-lock.json"}}
          paths:
            - ./node_modules 

      - run:
          name: Initializing the Environment variables
          command: |
            echo "REACT_APP_SECRET_KEY=$REACT_APP_SECRET_KEY
            REACT_APP_APP_IDL=$REACT_APP_APP_ID" > .env 

      - run: npm run build

      - run: yarn netlify:deploy

workflows:
  orb-free-workflow:
    jobs:
      - build
